In [1]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
list_of_lists=np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
num=np.arange(1,20)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
num1=np.arange(1,30,3)
num1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [13]:
num3=np.zeros(5)
num3

array([0., 0., 0., 0., 0.])

In [14]:
num4=np.zeros(10,int)
num4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
num5=np.ones(5)
num5

array([1., 1., 1., 1., 1.])

In [16]:
num6=np.ones(10,int)
num6

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])